version: '3'
services:
    currency-exchange:
        container_name: currency-exchange
        build:
            context: .
            dockerfile: Dockerfile
        image: sourav2804/aws-currency-exchange-service-h2
        ports:
          - "8000:8000"